apiVersion: apps/v1
kind: Deployment
metadata:
  name: step07-nodeport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: step07
  template:
    metadata:
      labels:
        app: step07
    spec:
      containers:
        - name: step07
          image: yejin00/step07-cicd
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: step07-nodeport-service
spec:
  selector:
    app: step07
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080  # NodePort 범위 내에서 선택
  type: NodePort