apiVersion: apps/v1
kind: Deployment
metadata:
  name: step07-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: step07-lb
  template:
    metadata:
      labels:
        app: step07-lb
    spec:
      containers:
        - name: step07
          image: yejin00/step07-cicd
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: step07-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: step07-lb
  ports:
    - protocol: TCP
      port: 8081        # 외부에서 접속할 포트
      targetPort: 8081  # 컨테이너에서 열려 있는 포트